# Claves obligatorias de SonarCloud
sonar.projectKey=FernandoMDFK_auth-service-espam
sonar.organization=fernandomdfk
sonar.host.url=https://sonarcloud.io

# Carpetas que se van a analizar (la carpeta src contiene tu código NestJS)
sonar.sources=src

# Archivos o carpetas que vamos a ignorar del análisis de seguridad
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts

# Idioma y codificación del proyecto
sonar.sourceEncoding=UTF-8